-- 客户报货是唯一客户需求与库存预留入口；转换后进入标准销售单链路。

CREATE TABLE IF NOT EXISTS `{{prefix}}customer_report` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '客户报货单ID',
  `tenant_id` int(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT '租户ID',
  `sn` varchar(64) NOT NULL DEFAULT '' COMMENT '报货单号',
  `main_customer_id` int(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT '结算主客户ID',
  `main_customer_name` varchar(100) NOT NULL DEFAULT '' COMMENT '结算主客户名称快照',
  `status` varchar(32) NOT NULL DEFAULT 'submitted_ready' COMMENT 'submitted_ready/submitted_shortage/completed/cancelled',
  `total_base_qty` decimal(18,2) NOT NULL DEFAULT 0.00 COMMENT '基础单位总需求',
  `reserved_base_qty` decimal(18,2) NOT NULL DEFAULT 0.00 COMMENT '已预留基础单位总量',
  `shortage_base_qty` decimal(18,2) NOT NULL DEFAULT 0.00 COMMENT '缺货基础单位总量',
  `idempotency_key` varchar(96) NOT NULL DEFAULT '' COMMENT '提交幂等键',
  `request_fingerprint` char(64) NOT NULL DEFAULT '' COMMENT '提交请求摘要',
  `version` int(11) UNSIGNED NOT NULL DEFAULT 1 COMMENT '乐观锁版本',
  `submitted_time` int(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT '提交时间',
  `remark` varchar(500) NOT NULL DEFAULT '' COMMENT '备注',
  `create_time` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `update_time` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `delete_time` int(11) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_customer_report_sn` (`tenant_id`,`sn`),
  UNIQUE KEY `uk_tenant_customer_report_idempotency` (`tenant_id`,`idempotency_key`),
  KEY `idx_tenant_customer_report_status` (`tenant_id`,`main_customer_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='独立客户报货单';

CREATE TABLE IF NOT EXISTS `{{prefix}}customer_report_item` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '报货行ID',
  `tenant_id` int(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT '租户ID',
  `report_id` int(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT '客户报货单ID',
  `main_customer_id` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `main_customer_name` varchar(100) NOT NULL DEFAULT '',
  `delivery_customer_id` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `delivery_customer_name` varchar(100) NOT NULL DEFAULT '',
  `warehouse_id` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `goods_id` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `goods_name` varchar(200) NOT NULL DEFAULT '',
  `goods_code` varchar(100) NOT NULL DEFAULT '',
  `sku_id` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `quality_id` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `spec_id` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `unit_id` int(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT '报货单位',
  `unit_name` varchar(50) NOT NULL DEFAULT '',
  `base_unit_id` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `base_unit_name` varchar(50) NOT NULL DEFAULT '',
  `order_qty` decimal(18,2) NOT NULL DEFAULT 0.00 COMMENT '原始报货数量',
  `expected_base_qty` decimal(18,2) NOT NULL DEFAULT 0.00 COMMENT '后端重算基础单位需求',
  `reserved_base_qty` decimal(18,2) NOT NULL DEFAULT 0.00,
  `shortage_base_qty` decimal(18,2) NOT NULL DEFAULT 0.00,
  `fulfilled_base_qty` decimal(18,2) NOT NULL DEFAULT 0.00,
  `piece_weight_min` decimal(18,2) NOT NULL DEFAULT 0.00,
  `piece_weight_max` decimal(18,2) NOT NULL DEFAULT 0.00,
  `piece_weight_confirmed` tinyint(1) UNSIGNED NOT NULL DEFAULT 0,
  `quality_snapshot` varchar(100) NOT NULL DEFAULT '',
  `specification_snapshot` varchar(100) NOT NULL DEFAULT '',
  `processing_requirement` varchar(255) NOT NULL DEFAULT '',
  `price_status` varchar(32) NOT NULL DEFAULT 'unpriced' COMMENT 'unpriced/priced',
  `price` decimal(18,2) NOT NULL DEFAULT 0.00,
  `pricing_unit_id` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `pricing_unit_name` varchar(50) NOT NULL DEFAULT '',
  `status` varchar(32) NOT NULL DEFAULT 'submitted_ready',
  `line_remark` varchar(500) NOT NULL DEFAULT '',
  `sort` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `create_time` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `update_time` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `delete_time` int(11) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_tenant_customer_report_item_report` (`tenant_id`,`report_id`,`delete_time`),
  KEY `idx_tenant_customer_report_item_goods` (`tenant_id`,`warehouse_id`,`goods_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='独立客户报货行';

CREATE TABLE IF NOT EXISTS `{{prefix}}customer_report_reservation` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '客户报货库存预留记录ID',
  `tenant_id` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `report_id` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `report_item_id` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `warehouse_id` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `goods_id` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `reserved_base_qty` decimal(18,2) NOT NULL DEFAULT 0.00,
  `consumed_base_qty` decimal(18,2) NOT NULL DEFAULT 0.00,
  `released_base_qty` decimal(18,2) NOT NULL DEFAULT 0.00,
  `status` varchar(32) NOT NULL DEFAULT 'reserved' COMMENT 'reserved/fulfilled/released',
  `create_time` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `update_time` int(11) UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_customer_report_reservation_item` (`tenant_id`,`report_item_id`),
  KEY `idx_tenant_customer_report_reservation_report` (`tenant_id`,`report_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='独立客户报货库存预留';

CREATE TABLE IF NOT EXISTS `{{prefix}}customer_goods_report_preference` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '客户商品报货偏好ID',
  `tenant_id` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `customer_id` int(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配送客户ID',
  `goods_id` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `unit_id` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `unit_name` varchar(50) NOT NULL DEFAULT '',
  `piece_weight_min` decimal(18,2) NOT NULL DEFAULT 0.00,
  `piece_weight_max` decimal(18,2) NOT NULL DEFAULT 0.00,
  `confirmed_by` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `confirmed_time` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `create_time` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `update_time` int(11) UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_customer_goods_report_preference` (`tenant_id`,`customer_id`,`goods_id`),
  KEY `idx_tenant_customer_goods_report_preference_goods` (`tenant_id`,`goods_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='客户商品报货重量偏好（仅建议）';
