$ErrorActionPreference='Stop'
$root='E:\object\BeiMi\BeiMi-PHP'; $base=Join-Path $root '.codex\retirement-snapshots'; $temp=Join-Path $base '.jxc-baseline-20260724T132353994-91a86a18-tmp'; $final=Join-Path $base 'jxc-baseline-20260724T132353994-91a86a18'
$paths=@('app/api/jxc/controller/AuthController.php','app/api/jxc/controller/BaseJxcController.php','app/api/jxc/controller/SupplyOrderController.php','app/api/jxc/logic/CustomerLogic.php','app/api/jxc/logic/PurchaseReturnOrderLogic.php','app/api/jxc/logic/SalesOrderLogic.php','app/api/jxc/logic/SalesReturnOrderLogic.php','app/api/jxc/logic/StoreLogic.php','app/api/jxc/logic/SupplierLogic.php','app/api/jxc/logic/SupplyOrderLogic.php','app/api/jxc/middleware/JxcLoginMiddleware.php','app/api/jxc/validate/SalesOrderValidate.php','app/api/jxc/validate/SupplyOrderValidate.php')|Sort-Object
$utf8=[Text.UTF8Encoding]::new($false)
function R([string]$p){$b=[IO.File]::ReadAllBytes((Join-Path $root $p));[pscustomobject]@{relative_path=$p;bytes=$b.Length;sha256=[Convert]::ToHexString([Security.Cryptography.SHA256]::HashData($b)).ToLowerInvariant()}}
function A([string]$head,[object[]]$s){if((git -C $root rev-parse HEAD).Trim() -ne $head){throw 'HEAD changed'};$x=@(git -C $root status --porcelain=v1 -- $paths);$w=@($paths|%{" M $_"});if($x.Count -ne 13 -or @(Compare-Object $w $x).Count){throw 'status changed'};git -C $root diff --cached --quiet -- $paths;if($LASTEXITCODE){throw 'staged'};foreach($q in $s){$a=R $q.relative_path;if($a.bytes -ne $q.bytes -or $a.sha256 -ne $q.sha256){throw "bytes changed $($q.relative_path)"}}}
if(Test-Path -LiteralPath $final){throw 'final collision'}
$prior=Join-Path $base 'current-20260724T105744+0800-067338f6';$expect=((Get-Content -Raw (Join-Path $prior 'archive.sha256')).Trim()-split '\s+')[0].ToLowerInvariant();$got=(Get-FileHash (Join-Path $prior 'BeiMi-PHP-current-20260724T105744+0800-067338f6.zip') -Algorithm SHA256).Hash.ToLowerInvariant();if($expect -ne $got){throw 'provenance hash mismatch'}
$head=(git -C $root rev-parse HEAD).Trim();$s=@($paths|%{R $_});A $head $s
$status=@(git -C $root status --porcelain=v1 -- $paths);$diff=[string](git -C $root diff --binary --full-index --no-ext-diff -- $paths|Out-String);if(@([regex]::Matches($diff,'(?m)^diff --git a/')).Count -ne 12){throw 'patch count'};foreach($p in @('-----BEGIN (?:RSA |EC |OPENSSH |DSA )?PRIVATE KEY-----','AKIA[0-9A-Z]{16}','(?i)(?:password|passwd|pwd)\s*[:=]\s*["''][^"'']{8,}','(?i)(?:api[_-]?key|secret|token)\s*[:=]\s*["''][A-Za-z0-9_-]{16,}["'']')){if([regex]::IsMatch($diff,$p)){throw 'sensitive patch'}}
$readme="# JXC detection baseline`n`nThis is a detection baseline only. It is not a restore package and contains no JXC source-file archive.`n`nCompare current raw bytes in `jxc-files-sha256.tsv`, target-only porcelain output, and patch-path count before supplier retirement. On mismatch, stop; do not overwrite.`n`nJXC (`app/api/jxc`) is excluded from supplier retirement. The prior snapshot is byte-equality provenance only, never a restore source.`n"
[IO.File]::WriteAllText((Join-Path $temp 'README.md'),$readme,$utf8);[IO.File]::WriteAllText((Join-Path $temp 'jxc-status--porcelain-v1.txt'),(($status -join "`n")+"`n"),$utf8);[IO.File]::WriteAllText((Join-Path $temp 'jxc-diff--binary.patch'),$diff.Replace("`r`n","`n"),$utf8);$tsv="relative_path`tbytes`tsha256`n"+(($s|%{"$($_.relative_path)`t$($_.bytes)`t$($_.sha256}" )-join "`n")+"`n";[IO.File]::WriteAllText((Join-Path $temp 'jxc-files-sha256.tsv'),$tsv,$utf8)
$peers=@('README.md','jxc-status--porcelain-v1.txt','jxc-diff--binary.patch','jxc-files-sha256.tsv');$hash=[ordered]@{};foreach($f in $peers){$hash[$f]=(Get-FileHash (Join-Path $temp $f) -Algorithm SHA256).Hash.ToLowerInvariant()};$meta=[ordered]@{format_version=1;created_at=(Get-Date).ToString('o');git_head=$head;paths=@($paths);path_count=13;patch_path_count=12;artifact_sha256=$hash;provenance='current-20260724T105744+0800-067338f6';provenance_claim='byte_equal_only_not_restore_source'}|ConvertTo-Json -Depth 4;[IO.File]::WriteAllText((Join-Path $temp 'metadata.json'),($meta+"`n"),$utf8)
Remove-Item -LiteralPath $PSCommandPath -Force
$expectFiles=@('README.md','metadata.json','jxc-status--porcelain-v1.txt','jxc-diff--binary.patch','jxc-files-sha256.tsv')|Sort-Object;$actual=@(Get-ChildItem $temp -Force -File|% Name|Sort-Object);if(@(Compare-Object $expectFiles $actual).Count){throw 'artifact set'};foreach($f in $peers){if((Get-FileHash (Join-Path $temp $f) -Algorithm SHA256).Hash.ToLowerInvariant() -ne $hash[$f]){throw 'rehash'}};$m=Get-Content (Join-Path $temp 'jxc-files-sha256.tsv');if($m.Count -ne 14 -or $m[0] -ne "relative_path`tbytes`tsha256" -or @($m[1..13]|%{($_ -split "`t")[0]}) -cne $paths){throw 'manifest'};git -C $root diff --check -- $paths;if($LASTEXITCODE){throw 'diff check'};A $head $s;[IO.File]::WriteAllBytes((Join-Path $temp 'READY'),[byte[]]@());if((Get-Item (Join-Path $temp 'READY')).Length){throw 'ready'};if(@(Compare-Object (@($expectFiles+'READY'|Sort-Object)) @(Get-ChildItem $temp -Force -File|% Name|Sort-Object)).Count){throw 'final set'};A $head $s;Move-Item -LiteralPath $temp -Destination $final;Write-Output $final
